[workspace]
members = [
#    "packages/spartan_wasm",
    "packages/secq256k1",
#    "packages/poseidon",
    "packages/hoplite",
    "packages/hoplite_circuit",
    "packages/poseidon",
    "packages/Spartan-secq",
    "packages/circuit_reader",
]